export const data = {
  "status": "OK",
  "request_id": "d7c61405-3de5-494c-910e-0a0b1d64b14e",
  "parameters": {
    "query": "Phone",
    "country": "US",
    "sort_by": "RELEVANCE",
    "page": 1,
    "is_prime": false,
    "language": "en_US"
  },
  "data": {
    "total_products": 150816,
    "country": "US",
    "domain": "www.amazon.com",
    "products": [
      {
        "asin": "B0F7M1D1Z9",
        "product_title": "Tracfone Moto G Play (2023) [Activation Promotion], 32GB, Blue, Includes 1500Min/1500Txt/1500MB, 365 Days Service Plan - Prepaid Smartphone",
        "product_price": "$49.99",
        "product_original_price": null,
        "currency": "USD",
        "product_star_rating": "4.3",
        "product_num_ratings": 1095,
        "product_url": "https://www.amazon.com/dp/B0F7M1D1Z9",
        "product_photo": "https://m.media-amazon.com/images/I/61Ydn7qAodL._AC_UY654_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "$49.99",
        "is_best_seller": false,
        "is_amazon_choice": true,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "2K+ bought in past month",
        "delivery": "FREE delivery Tue, Aug 5Or fastest delivery Overnight 4 AM - 8 AM",
        "has_variations": false,
        "product_badge": "Overall Pick"
      },
      {
        "asin": "B0CP6DDN1H",
        "product_title": "Motorola Moto G Play | 2024 | Unlocked | Made for US 4/64GB | 50MP Camera | Sapphire Blue",
        "product_price": "$109.99",
        "product_original_price": "$149.99",
        "currency": "USD",
        "product_star_rating": "4.2",
        "product_num_ratings": 2629,
        "product_url": "https://www.amazon.com/dp/B0CP6DDN1H",
        "product_photo": "https://m.media-amazon.com/images/I/61xk4XNRktL._AC_UY654_FMwebp_QL65_.jpg",
        "product_num_offers": 6,
        "product_minimum_offer_price": "$98.99",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "5K+ bought in past month",
        "delivery": "FREE delivery Tue, Aug 5Or fastest delivery Overnight 4 AM - 8 AM",
        "has_variations": true
      },
      {
        "asin": "B0BN72FYFG",
        "product_title": "Apple iPhone 14, 128GB, Midnight - Unlocked (Renewed)",
        "product_price": "$339.38",
        "product_original_price": "$389.00",
        "currency": "USD",
        "product_star_rating": "4.1",
        "product_num_ratings": 5866,
        "product_url": "https://www.amazon.com/dp/B0BN72FYFG",
        "product_photo": "https://m.media-amazon.com/images/I/61WUSYIQdKL._AC_UY654_FMwebp_QL65_.jpg",
        "product_num_offers": 51,
        "product_minimum_offer_price": "$314.44",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "product_availability": "Only 10 left in stock - order soon.",
        "climate_pledge_friendly": false,
        "sales_volume": "5K+ bought in past month",
        "delivery": "FREE delivery Fri, Aug 8Or fastest delivery Mon, Aug 4Only 10 left in stock - order soon.",
        "has_variations": true
      },
      {
        "asin": "B0DLHLRDBY",
        "product_title": "Samsung Galaxy A16 5G A Series, Unlocked Android Smartphone, Large AMOLED Display, Durable Design, Super Fast Charging, Expandable Storage, 5G Connectivity, US Version, 2025, Light Gray EPEAT ECOLOGO",
        "product_price": "$199.99",
        "product_original_price": null,
        "currency": "USD",
        "product_star_rating": "4.2",
        "product_num_ratings": 1353,
        "product_url": "https://www.amazon.com/dp/B0DLHLRDBY",
        "product_photo": "https://m.media-amazon.com/images/I/71VV0kyOKCL._AC_UY654_FMwebp_QL65_.jpg",
        "product_num_offers": 2,
        "product_minimum_offer_price": "$171.54",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": true,
        "sales_volume": "7K+ bought in past month",
        "delivery": "FREE delivery Tue, Aug 5Or fastest delivery Overnight 4 AM - 8 AM",
        "has_variations": true
      },
      {
        "asin": "B0DT4T8D65",
        "product_title": "SAMSUNG Galaxy A16 4G LTE (128GB + 4GB) International Model SM-A165F/DS Factory Unlocked 6.7&quot; Dual Sim 50MP Dual Cam (Case Bundle) (Gray)",
        "product_price": "$130.99",
        "product_original_price": null,
        "currency": "USD",
        "product_star_rating": "3.8",
        "product_num_ratings": 1065,
        "product_url": "https://www.amazon.com/dp/B0DT4T8D65",
        "product_photo": "https://m.media-amazon.com/images/I/51Rn-9C6xQL._AC_UY654_FMwebp_QL65_.jpg",
        "product_num_offers": 16,
        "product_minimum_offer_price": "$109.50",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "1K+ bought in past month",
        "delivery": "FREE delivery Tue, Aug 5Or fastest delivery Tomorrow, Aug 1",
        "has_variations": true
      },
      {
        "asin": "B0BZG14KFJ",
        "product_title": "Panasonic Cordless Phone with Answering Machine, Advanced Call Block, Bilingual Caller ID and Easy to Read High-Contrast Display, Expandable System with 2 Handsets - KX-TGD832M (Metallic Black)",
        "product_price": "$57.95",
        "unit_price": "$28.98",
        "unit_count": 2,
        "product_original_price": null,
        "currency": "USD",
        "product_star_rating": "4.3",
        "product_num_ratings": 6352,
        "product_url": "https://www.amazon.com/dp/B0BZG14KFJ",
        "product_photo": "https://m.media-amazon.com/images/I/81nkYlfA5ZL._AC_UY654_FMwebp_QL65_.jpg",
        "product_num_offers": 6,
        "product_minimum_offer_price": "$36.45",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "8K+ bought in past month",
        "delivery": "FREE delivery Tue, Aug 5Or fastest delivery Overnight 4 AM - 8 AM",
        "has_variations": false
      },
      {
        "asin": "B0FH7QM1QV",
        "product_title": "Motorola Moto G 5G | 2024 | Consumer Cellular | Made for US 4/128GB | 50MP Camera | Sage Green",
        "product_price": "$99.99",
        "product_original_price": null,
        "currency": "USD",
        "product_star_rating": null,
        "product_num_ratings": 0,
        "product_url": "https://www.amazon.com/dp/B0FH7QM1QV",
        "product_photo": "https://m.media-amazon.com/images/I/61FA40vrrAL._AC_UY654_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "$99.99",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "product_availability": "Only 16 left in stock - order soon.",
        "climate_pledge_friendly": false,
        "sales_volume": null,
        "delivery": "FREE delivery Aug 7 - 13Or fastest delivery Mon, Aug 4Only 16 left in stock - order soon.",
        "has_variations": false
      },
      {
        "asin": "B0F9QY6M52",
        "product_title": "BLU G64L | 2025 | Unlocked | 6.8” HD+ Infinity Display | 64/4GB | Triple 13MP Camera | US Version | US Warranty | Green",
        "product_price": "$69.99",
        "product_original_price": null,
        "currency": "USD",
        "product_star_rating": "4.1",
        "product_num_ratings": 39,
        "product_url": "https://www.amazon.com/dp/B0F9QY6M52",
        "product_photo": "https://m.media-amazon.com/images/I/81hPLP-l2BL._AC_UY654_FMwebp_QL65_.jpg",
        "product_num_offers": 3,
        "product_minimum_offer_price": "$69.50",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "500+ bought in past month",
        "delivery": "FREE delivery Tue, Aug 5Or fastest delivery Tomorrow, Aug 1",
        "has_variations": true
      },
      {
        "asin": "B09V5LDZQ4",
        "product_title": "Samsung Galaxy S22 Smartphone, Factory Unlocked Android Cell Phone, 128GB, 8K Camera &amp; Video, Brightest Display, Long Battery Life, Fast 4nm Processor, US Version, Phantom Black (Renewed)",
        "product_price": "$196.33",
        "product_original_price": "$206.99",
        "currency": "USD",
        "product_star_rating": "3.9",
        "product_num_ratings": 3487,
        "product_url": "https://www.amazon.com/dp/B09V5LDZQ4",
        "product_photo": "https://m.media-amazon.com/images/I/61M4ndNetDL._AC_UY654_FMwebp_QL65_.jpg",
        "product_num_offers": 65,
        "product_minimum_offer_price": "$164.00",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "product_availability": "Only 7 left in stock - order soon.",
        "climate_pledge_friendly": false,
        "sales_volume": "2K+ bought in past month",
        "delivery": "FREE delivery Sat, Aug 2Or fastest delivery Tomorrow, Aug 1Only 7 left in stock - order soon.",
        "has_variations": true
      },
      {
        "asin": "B0D48Z3ZCH",
        "product_title": "Cheap Mobile Phones, 5.0 Inch, Android 9.0, Dual SIM Dual Camera, Quad Core, 16GB ROM【Expandable up to 128GB】, Support WiFi/Bluetooth/FM, Face Unlocked Phones (Purple)",
        "product_price": "$49.99",
        "product_original_price": null,
        "currency": "USD",
        "product_star_rating": "3",
        "product_num_ratings": 248,
        "product_url": "https://www.amazon.com/dp/B0D48Z3ZCH",
        "product_photo": "https://m.media-amazon.com/images/I/61VlDsUg1QL._AC_UY654_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "$49.99",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "100+ bought in past month",
        "delivery": "FREE delivery Tue, Aug 5Or fastest delivery Tomorrow, Aug 1",
        "has_variations": true
      },
      {
        "asin": "B084KS5WYC",
        "product_title": "Samsung Galaxy A10e 32GB A102U GSM Unlocked Phone - Black (Renewed)",
        "product_price": "$62.00",
        "product_original_price": "$68.44",
        "currency": "USD",
        "product_star_rating": "3.9",
        "product_num_ratings": 3780,
        "product_url": "https://www.amazon.com/dp/B084KS5WYC",
        "product_photo": "https://m.media-amazon.com/images/I/71Eh6YWqqyL._AC_UY654_FMwebp_QL65_.jpg",
        "product_num_offers": 19,
        "product_minimum_offer_price": "$59.11",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "1K+ bought in past month",
        "delivery": "FREE delivery Tomorrow, Aug 1",
        "has_variations": false
      },
      {
        "asin": "B09VH9BKHS",
        "product_title": "Samsung Galaxy S22+ 5G S906U 128GB GSM/CDMA Unlocked Android Smartphone (USA Version) - Phantom Black (Renewed)",
        "product_price": "$219.00",
        "product_original_price": "$899.00",
        "currency": "USD",
        "product_star_rating": "4.1",
        "product_num_ratings": 2155,
        "product_url": "https://www.amazon.com/dp/B09VH9BKHS",
        "product_photo": "https://m.media-amazon.com/images/I/61R5xNY4ZWL._AC_UY654_FMwebp_QL65_.jpg",
        "product_num_offers": 42,
        "product_minimum_offer_price": "$184.00",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "1K+ bought in past month",
        "delivery": "FREE delivery Tomorrow, Aug 1",
        "has_variations": true
      },
      {
        "asin": "B08HC5GMK2",
        "product_title": "Samsung Galaxy A11 32GB A115U Fully Unlocked Smartphones (Renewed)",
        "product_price": "$74.11",
        "product_original_price": "$78.44",
        "currency": "USD",
        "product_star_rating": "4",
        "product_num_ratings": 1260,
        "product_url": "https://www.amazon.com/dp/B08HC5GMK2",
        "product_photo": "https://m.media-amazon.com/images/I/51y-JGU66-L._AC_UY654_FMwebp_QL65_.jpg",
        "product_num_offers": 14,
        "product_minimum_offer_price": "$71.88",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "product_availability": "Only 16 left in stock - order soon.",
        "climate_pledge_friendly": false,
        "sales_volume": "300+ bought in past month",
        "delivery": "FREE delivery Mon, Aug 4Only 16 left in stock - order soon.",
        "has_variations": false
      },
      {
        "asin": "B09VD33WHW",
        "product_title": "SAMSUNG Galaxy S22 Ultra 5G, US Version, 128GB, Black - Unlocked (Renewed)",
        "product_price": "$338.00",
        "product_original_price": "$359.55",
        "currency": "USD",
        "product_star_rating": "3.7",
        "product_num_ratings": 6035,
        "product_url": "https://www.amazon.com/dp/B09VD33WHW",
        "product_photo": "https://m.media-amazon.com/images/I/613Fp7fknhL._AC_UY654_FMwebp_QL65_.jpg",
        "product_num_offers": 50,
        "product_minimum_offer_price": "$294.86",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "product_availability": "Only 15 left in stock - order soon.",
        "climate_pledge_friendly": false,
        "sales_volume": "1K+ bought in past month",
        "delivery": "FREE delivery Tomorrow, Aug 1Only 15 left in stock - order soon.",
        "has_variations": true
      },
      {
        "asin": "B0D7HWJDQM",
        "product_title": "Google Pixel 9 - Unlocked Android Smartphone with Gemini, 24-Hour Battery, Advanced Camera, and 6.3&quot; Actua Display - Obsidian - 128 GB ECOLOGO",
        "product_price": "$779.97",
        "product_original_price": null,
        "currency": "USD",
        "product_star_rating": "4.5",
        "product_num_ratings": 717,
        "product_url": "https://www.amazon.com/dp/B0D7HWJDQM",
        "product_photo": "https://m.media-amazon.com/images/I/61fh21u3DJL._AC_UY654_FMwebp_QL65_.jpg",
        "product_num_offers": 4,
        "product_minimum_offer_price": "$652.57",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "product_availability": "Only 2 left in stock - order soon.",
        "climate_pledge_friendly": true,
        "sales_volume": "2K+ bought in past month",
        "delivery": "FREE delivery Aug 6 - 8Or fastest delivery Tomorrow, Aug 1Only 2 left in stock - order soon.",
        "has_variations": true
      },
      {
        "asin": "B0DPQB114Y",
        "product_title": "Cheap Mobile Phones, 5.0&quot; IPS Display, Android 9.0, Dual SIM Dual Camera, Quad Core, 16GB ROM【Expandable up to 128GB】, Support WiFi/Bluetooth/FM, Face Unlocked Phones (Reno9pro-Ching)",
        "product_price": "$49.98",
        "product_original_price": null,
        "currency": "USD",
        "product_star_rating": "3.4",
        "product_num_ratings": 125,
        "product_url": "https://www.amazon.com/dp/B0DPQB114Y",
        "product_photo": "https://m.media-amazon.com/images/I/61Zq2GYuL1L._AC_UY654_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "$49.98",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "50+ bought in past month",
        "delivery": "FREE delivery Tue, Aug 5Or fastest delivery Tomorrow, Aug 1",
        "has_variations": true
      }
    ]
  }
}